name: shopeefood
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  cloud_firestore: ^6.6.0
  crypto: ^3.0.7
  firebase_core: ^4.11.0
  flutter:
    sdk: flutter
  flutter_map: ^8.3.1
  geocoding: ^5.0.0
  geolocator: ^14.0.3
  google_fonts: ^6.2.1
  http: ^1.6.0
  latlong2: ^0.10.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/categories/
    - assets/images/
    - assets/images/banners/
    - assets/images/restaurants/
