// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9cJ_z21pePLrfBM1LP8hVjHfCzzq48l0',
    appId: '1:134436958243:web:087b284df3785ed96e4196',
    messagingSenderId: '134436958243',
    projectId: 'shopeefood-6a82f',
    authDomain: 'shopeefood-6a82f.firebaseapp.com',
    storageBucket: 'shopeefood-6a82f.firebasestorage.app',
    measurementId: 'G-L8GKXVM6F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmgF6it19XvirNPm2_qbBJKQclnb943pY',
    appId: '1:134436958243:android:45576cd98681b5246e4196',
    messagingSenderId: '134436958243',
    projectId: 'shopeefood-6a82f',
    storageBucket: 'shopeefood-6a82f.firebasestorage.app',
  );
}
